package com.example.backend.constant.enums;

public enum NotificationType {
    APPOINTMENT_REMINDER, APPOINTMENT_CONFIRMATION, APPOINTMENT_CREATED, APPOINTMENT_CONFIRMED, APPOINTMENT_REJECTED, APPOINTMENT_COMPLETED, DOCTOR_NEW_APPOINTMENT_REQUEST, DOCTOR_APPOINTMENT_CANCELLED, TIME_OFF_APPROVED, TIME_OFF_REJECTED, PAYMENT_SUCCESS, GENERAL_ANNOUNCEMENT
}
